name: clang-tidy-review

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ZedThree/clang-tidy-review@v0.12.0
      id: review
      with:
        apt_packages: git g++ libqt5opengl5-dev libqt5svg5-dev libglvnd-dev libeigen3-dev zlib1g-dev libfftw3-dev ninja-build
        cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on

    - uses: ZedThree/clang-tidy-review/upload@v0.12.0
      id: upload-review
