name: nightly-builds

on:
  # Run this every hour
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
      
jobs:
  linux-nightly-release:
    runs-on: ubuntu-20.04
    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_SIZE: "2G"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Install Qt 6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.1'
        set-env: true
    
    - name: Run sccache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Run tarball script
      id: package
      run: |
        ./packaging/package-linux-tarball.sh .
        mv mrtrix.tar.gz mrtrix3-linux-${{ github.sha }}.tar.gz

    - name: Upload linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: mrtrix3-linux-${{ github.sha }}.tar.gz
        path: mrtrix3-linux-${{ github.sha }}.tar.gz

  macos-nightly-release:
    runs-on: macos-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_CACHE_MULTIARCH: "true"
      SCCACHE_SIZE: "2G"
      PACKAGES: "qt eigen pkg-config fftw libpng ninja cmake"

    steps:
      - name: Fetch recipe
        run: git clone https://github.com/mrtrix3/macos-installer.git -b cmake_qt6_universal
      
      - name: install dependencies
        run: |
          brew update || brew update     # https://github.com/Homebrew/brew/issues/2491#issuecomment-294207661
          brew install $PACKAGES || brew install $PACKAGES
          brew link --force qt

      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Build package
        run: |
          ./build dev
          ls
          mv mrtrix3-macos-dev.tar.xz ../mrtrix3-macos-${{ github.sha }}.tar.xz
        working-directory: ./macos-installer

      - name: Upload macos artifact
        uses: actions/upload-artifact@v4
        with:
          name: mrtrix3-macos-${{ github.sha }}.tar.xz
          path: mrtrix3-macos-${{ github.sha }}.tar.xz

  windows-nightly-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    env:
      CHERE_INVOKING: enabled_from_arguments
      MINGW_PACKAGE_PREFIX: mingw-w64-ucrt-x86_64
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_CACHE_SIZE: "2G"
      SCCACHE_DIR: ${{ github.workspace }}/.sccache

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          release: false
          install: |
            git
            python
            ${{env.MINGW_PACKAGE_PREFIX}}-bc
            ${{env.MINGW_PACKAGE_PREFIX}}-cmake
            ${{env.MINGW_PACKAGE_PREFIX}}-diffutils
            ${{env.MINGW_PACKAGE_PREFIX}}-eigen3
            ${{env.MINGW_PACKAGE_PREFIX}}-fftw
            ${{env.MINGW_PACKAGE_PREFIX}}-gcc
            ${{env.MINGW_PACKAGE_PREFIX}}-libtiff
            ${{env.MINGW_PACKAGE_PREFIX}}-ninja
            ${{env.MINGW_PACKAGE_PREFIX}}-pkg-config
            ${{env.MINGW_PACKAGE_PREFIX}}-qt6-base
            ${{env.MINGW_PACKAGE_PREFIX}}-qt6-svg
            ${{env.MINGW_PACKAGE_PREFIX}}-zlib

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: export sccache to msys2 shell
        run: |
          export SCCACHE_UNIX_PATH=$(cygpath -u "$SCCACHE_PATH")
          SCCACHE_DIR=$(dirname "$SCCACHE_UNIX_PATH")
          echo "export PATH=$SCCACHE_DIR:$PATH" >> $GITHUB_ENV

      - name: Clone packaging repo
        run: git clone https://github.com/daljit46/MINGW

      - name: Build package
        run: |
          cd MINGW
          ./run.sh ${{ github.sha }} daljit46
          mv mingw*.tar.zst ../mrtrix3-windows-${{ github.sha }}.tar.xz

      - name: Upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: mrtrix3-windows-${{ github.sha }}.tar.gz
          path: mrtrix3-windows-${{ github.sha }}.tar.xz

  update-nightly-version:
    runs-on: ubuntu-latest
    needs: [linux-nightly-release, macos-nightly-release, windows-nightly-release]
    steps:
      - name: Download Artifacts from previous jobs
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: mrtrix3-*
          merge-multiple: true

      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'MRtrix3 Nightly Release $$'
          prerelease: true
          body: |
            This is an automated nightly build of MRtrix3.
            It is not intended for production use.
          files: |
            ./artifacts/*.tar.gz
            ./artifacts/*.tar.xz
