name: nightly-builds

on:
  # Run this every hour
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
      
jobs:
  linux-nightly-release:
    runs-on: ubuntu-20.04
    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_SIZE: "2G"

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install Qt 6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.6.1'
        set-env: true
    
    - name: Run sccache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Run tarball script
      id: package
      run: |
        ./packaging/package-linux-tarball.sh .
        mv mrtrix.tar.gz mrtrix-$(git describe --tags --abbrev=0)-linux.tar.gz
        # set the name of the tarball as an output
        # this will be used by the next step to upload the tarball
        echo "::set-output name=asset_path::mrtrix-$(git describe --tags --abbrev=0)-linux.tar.gz"

    - name: Upload linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: mrtrix3-linux-${{ github.sha }}.tar.gz
        path: ${{ steps.package.outputs.asset_path }}

  macos-nightly-release:
    runs-on: macos-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_CACHE_MULTIARCH: "true"
      SCCACHE_SIZE: "2G"
      PACKAGES: "qt eigen pkg-config fftw libpng ninja cmake"

    steps:
      - name: Fetch recipe
        run: git clone https://github.com/daljit46/macos-installer.git -b cmake_qt6_universal
      
      - name: install dependencies
        run: |
          brew update || brew update     # https://github.com/Homebrew/brew/issues/2491#issuecomment-294207661
          brew install $PACKAGES || brew install $PACKAGES
          brew link --force qt

      - name: Run sccache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Build package
        run: |
          ./build dev
        working-directory: ./macos-installer

      - name: Upload macos artifact
        uses: actions/upload-artifact@v4
        with:
          name: mrtrix3-macos-${{ github.sha }}.tar.gz
          path: ./macos-installer/mrtrix3-macos-dev.tar.xz

  update-nightly-version:
    runs-on: ubuntu-20.04
    needs: [linux-nightly-release, macos-nightly-release]
    steps:
      - name: Download Artifacts from previous jobs
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: mrtrix3-*
          merge-multiple: true

      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'MRtrix3 Nightly Release $$'
          prerelease: true
          body: |
            This is an automated nightly build of MRtrix3.
            It is not intended for production use.
          files:
            artifacts/*.tar.gz
            artifacts/*.tar.xz
