name: package-linux-tarball

on:
  release:
    types: [created]
      
jobs:
  package:
    runs-on: ubuntu-20.04
    # we run this workflow on ubuntu 18.04 to lower the minimum required glibc version
    container:
      image: ubuntu:18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
     
    - name: Build Qt 6
      run:
        git clone git://code.qt.io/qt/qt5.git
        cd qt5
        git checkout 6.6.1
        ./init-repository
        cmake -B build -DQT_BUILD_EXAMPLES=OFF -DQT_BUILD_TESTS=OFF
        cmake --build build
        cmake --install build --prefix /usr/local/qt6

    - name: Run tarball script
      run: |
        export CMAKE_PREFIX_PATH=/usr/local/qt6
        export QMAKE=/usr/local/qt6/bin/qmake
        export LD_LIBRARY_PATH=/usr/local/qt6/lib
        ./packaging/package-linux-tarball.sh .
        mv mrtrix.tar.gz mrtrix-$(git describe --tags --abbrev=0)-linux.tar.gz

    - name: Upload package to GitHub Release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: '*.tar.gz'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
