name: Build

on:
  push:
  workflow_dispatch:
      
jobs:
  linux-clang-build:
    runs-on: ubuntu-20.04

    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_CACHE_SIZE: "2G"

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: install dependencies
      run: | 
        sudo apt install cmake \
        libgl1-mesa-dev \
        ninja-build \
        python3 \
        libeigen3-dev \
        zlib1g-dev \
        libfftw3-dev \
        libtiff5-dev \
        libpng-dev

    - name: Install Clang 17
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'linux'
        arch: 'gcc_64'
        cache-key-prefix: 'install-qt-action'
        set-env: 'true'

    - name: configure
      run: >
        cmake
        -B build
        -G Ninja
        -D CMAKE_CXX_COMPILER=clang++-17
        -D CMAKE_BUILD_TYPE=Release
        -D MRTRIX_USE_QT6=ON

    - name: build
      run: cmake --build build

    - name: install
      run: cmake --install build --prefix ./mrtrix3_install

    - name: Run linuxdeploy
      run: |
        wget "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
        wget "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage"
        chmod +x ./linuxdeploy-x86_64.AppImage
        chmod +x ./linuxdeploy-plugin-qt-x86_64.AppImage
        mkdir appdir && mkdir appdir/usr
        cp -r mrtrix3_install/* appdir/usr
        ./linuxdeploy-x86_64.AppImage --appdir appdir --plugin qt --verbosity=0
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mrtrix3
        path: ${{ github.workspace }}/appdir/usr