name: Releases

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'master'

jobs:
  linux-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Install Eigen3
        run: |
          git clone https://gitlab.com/libeigen/eigen.git
          cd eigen && git checkout 3.4.0
          cmake -B build && cmake --build build
          sudo cmake --install build

      - name: Install Qt 6
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.0'
          set-env: true

      - name: Run build
        run: |
          ./packaging/package-linux-tarball.sh .
          mv mrtrix.tar.gz mrtrix-linux-${{ github.event.inputs.branch }}.tar.gz

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: mrtrix-linux-${{ github.event.inputs.branch }}
          path: mrtrix-linux-${{ github.event.inputs.branch }}.tar.gz

  macos-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: packaging_changes

      - name: Install deps
        run: brew install numpy cmake qt eigen pkg-config fftw libpng ninja

      - name: Run build
        run: |
          cd ./packaging/macos
          ./build ${{ github.event.inputs.branch }}
          ls
          mv ./mrtrix3-macos-${{ github.event.inputs.branch }}.tar.xz ../../

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: mrtrix-macos-${{ github.event.inputs.branch }}
          path: mrtrix-macos-${{ github.event.inputs.branch }}.tar.xz

  windows-release:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    env:
      MINGW_PACKAGE_PREFIX: mingw-w64-ucrt-x86_64

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: |
            git
            python
            ${{env.MINGW_PACKAGE_PREFIX}}-bc
            ${{env.MINGW_PACKAGE_PREFIX}}-cmake
            ${{env.MINGW_PACKAGE_PREFIX}}-diffutils
            ${{env.MINGW_PACKAGE_PREFIX}}-eigen3
            ${{env.MINGW_PACKAGE_PREFIX}}-fftw
            ${{env.MINGW_PACKAGE_PREFIX}}-gcc
            ${{env.MINGW_PACKAGE_PREFIX}}-libtiff
            ${{env.MINGW_PACKAGE_PREFIX}}-ninja
            ${{env.MINGW_PACKAGE_PREFIX}}-pkg-config
            ${{env.MINGW_PACKAGE_PREFIX}}-qt6-base
            ${{env.MINGW_PACKAGE_PREFIX}}-qt6-svg
            ${{env.MINGW_PACKAGE_PREFIX}}-zlib
      
      - name: Checkout
        run: git clone https://github.com/mrtrix3/mrtrix3 -b ${{ github.event.inputs.branch }}

      - name: Run build
        run: |
          cd mrtrix3
          commit_sha=$(git rev-parse HEAD)
          cd packaging/mingw
          ./run.sh $commit_sha mrtrix3
          mv mingw*.tar.zst ../../../mrtrix-windows-${{ github.event.inputs.branch }}.tar.zst

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: mrtrix-windows-${{ github.event.inputs.branch }}
          path: mrtrix-windows-${{ github.event.inputs.branch }}.tar.zst
